### PR TITLE
allow many-to-many sortable

### PR DESCRIPTION
**Pull request by digitalkaoz**
this PR allows `many-to-many` relations to be sortable (same as `one-to-many`)

### CODE REVIEW

**Comment by digitalkaoz** [comment]
any news on that?

**Comment by Soullivaneuh** [comment]
Could you please rebase your PR to make test working?

I have to test it manually after that.

**Comment by digitalkaoz** [comment]
done

**Comment by Soullivaneuh** [comment]
@digitalkaoz Could you please provide a concrete case I can test? With entity and admin classes.

Also as a sort of new feature, doc could also be updated, isn't it?

**Comment by digitalkaoz** [comment]
Oh its not a New feature, just the same as for on-to-many Relations

Sullivan SENECHAL <notifications@github.com> schrieb am Sa., 4. Juli 2015
17:15:

**Comment by Soullivaneuh** [comment]
Ok, waiting for a concrete case sample to be sure we are testing the same thing (not really using this feature actually). :+1:

**Comment by digitalkaoz** [comment]
the concrete case sample is "sortable for relations" currently only available for `one-to-many` now also for `many-to-many`

**Comment by OskarStark** [comment]
so you say you dind't change code, just activated already written code for many-to-many?

does the on-to-many case already has tests? i'm asking as you can then copy the tests and change it for many-to-many

**Comment by digitalkaoz** [comment]
yes a simply copy pasted some code from on-to-many... i guess there are no tests for it (as its a template /js feature only)

**Comment by Soullivaneuh** [comment]
@digitalkaoz I don't use sortable. Could you indicate me where I can test that on sonata-sandbox? Maybe a PR with this concrete case would be useful if not existing.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
