### PR TITLE
Moves crud association templates to admin-bundle

### PR DESCRIPTION
**Pull request by ju1ius**
This PR is related to [SonataAdminBundle#3971](https://github.com/sonata-project/SonataAdminBundle/pull/3971)
I am targetting this branch, because there are BC breaks
## Changelog

``` markdown
### Added
- `FieldDescription` implements `FieldDescriptionInterface::describesSingleValuedAssociation` and `FieldDescriptionInterface::describesCollectionValuedAssociation` methods

### Changed
- `FormContractor` now extends `Sonata\AdminBundle\Admin\AbstractFormContractor`

### Removed
- removed ALL crud association templates and form widget blocks. They now belong to the admin bundle

```

### CODE REVIEW

**Comment by core23** [comment]
Any updates on this @ju1ius ?

**Comment by OskarStark** [comment]
Any news here @ju1ius ?

**Comment by core23** [comment]
Can we close this, after merging this sonata-project/SonataDoctrineORMAdminBundle#772?

Please verify before closing!

**Comment by kunicmarko20** [comment]
Templates have already been moved, can we close this?

**Comment by jordisala1991** [comment]
there is one interesting thing, we moved those templates directly, but @ju1ius wanted to create like a common interface for every database integration. It was a little bit different. Not sure if this should be closed or not.

**Comment by kunicmarko20** [comment]
That is a great idea but sounds like a lot of work. Will leave it then, maybe someone revisits this in future.

**Comment by OskarStark** [comment]
No active work, so let's close it for now

**Pull request closed without merging**
