### PR TITLE
Reset page to first 3.1.4

### PR DESCRIPTION
**Pull request by mihail-intexsys**
## Changelog

```markdown

### Changed
- Added check if offset is higher or equals result count and forced to show 
results from the first page in such case.

### Fixes
- Fixes a bug when all items were deleted(with a batch deletion) from the second page on the admin list and we were redirected to the same page with empty result list and without page selector

### CODE REVIEW

**Comment by greg0ire** [comment]
I'd rather do this in the controller of the batch action, it will be easier to understand and will benefit other storage engines.

**Comment by mihail-intexsys** [comment]
There is also few more cases which are not related to batch deletion. 

- You can also delete 33rd item with 32 per page (first and only item on the second page) from the edit form and you will be redirected to empty page.
- You can share a url with applied filters on it (page and per page size) from the last page with someone and after time if items from the last page were deleted your url will be broken and behave like in previous described cases.

**Comment by greg0ire** [comment]
> You can share a url with applied filters on it (page and per page size) from the last page with someone and after time if items from the last page were deleted your url will be broken and behave like in previous described cases.

I'd expect this to give a 404

> You can also delete 33rd item with 32 per page (first and only item on the second page) from the edit form and you will be redirected to empty page.

I don't understand how

**Comment by mihail-intexsys** [comment]
Actually we managed to fix this issue in the listAction of extended sonataAdminBundle CRUDController , just redirecting to the first page if there is 0 results on current non first page, pretty similar like @greg0ire suggested in the first comment. I think pull request can be declined.

**Comment by greg0ire** [comment]
Thanks for following up on this!

**Pull request closed without merging**
