### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**
Just approve, don't merge.

### CODE REVIEW

**Comment by greg0ire** [comment]
The build is broken because of doctrine type hints, and I think this should be fixed on the stable branch

**Comment by jordisala1991** [comment]
Type hints or because of the strict type declaration?

**Comment by greg0ire** [comment]
unsure yet, but doctrine 2.6 is out, and I think it might have `string` type hints.

**Comment by greg0ire** [comment]
Extracting the interesting part: `/home/travis/build/sonata-project/SonataDoctrineORMAdminBundle/vendor/sonata-project/admin-bundle/src/Admin/BaseFieldDescription.php:265`

**Comment by greg0ire** [comment]
Leads to this: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/BaseFieldDescription.php#L265

**Comment by greg0ire** [comment]
might be fixed in this bundle since its a passthrough

**Comment by jordisala1991** [comment]
Ohh yes.. I see better now. We have to fix it on stable indeed, add a cast should fix it right?

**Comment by greg0ire** [comment]
Not sure yet, I think it might just be the tests that need fixing

**Comment by greg0ire** [comment]
Updating because I don't reproduce it locally, I must have an old version of doctrine

**Comment by greg0ire** [comment]
Ok now I reproduce the issue

**Comment by greg0ire** [comment]
See #793

**Pull request merged**
