### PR TITLE
Stop using deprecated FieldDescription methods

### LINKED ISSUE #1230: Deprecate ModelManager::getMetadata and ModelManager::hasMetadata
Similar to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/492

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

Closes #1230.

## Changelog

```markdown
### Deprecated
- Deprecated `ModelManager::getMetadata()` method.
- Deprecated `ModelManager::hasMetadata()` method.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @franmomu.

I was trying to reproduce the same PR you did on https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/492

But in the DatagridBuilder::fixFieldDescription method, there is a `if` you don't have in mongo persistence bundle.
Do you know how to handle it ? https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L94

**Comment by franmomu** [comment]
> Do you know if we still have to handle it ? https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L94

[I guess so, looks like that is for embeddables](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/816), what I don't know is why is this needed and is not handled "normally", maybe adding some tests with real classmetada would help. I think I could give it a try within the next days

**Comment by VincentLanglet** [comment]
> > Do you know if we still have to handle it ? https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L94
> 
> [I guess so, looks like that is for embeddables](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/816), what I don't know is why is this needed and is not handled "normally", maybe adding some tests with real classmetada would help. I think I could give it a try within the next days

I agree that it should be handled normally (or in a better way). But I know nothing about metadata, embeddable, ... (and doctrine in general).
So it would be a great help for me it you find times to give a try. This should be solved as soon as possible to be able again to merge 3.x into master (and having a working master branch).

**Comment by VincentLanglet** [comment]
I think this can be solved by https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1241

**Review by wbloszyk — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
