### PR TITLE
Drop Symfony 4.4 and Twig 2

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Removed
- Support for Symfony 4.4
- Support for Twig 2
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I have added more database versions to test (more postgres and mysql versions). Modified php version for those tests too.

**Comment by VincentLanglet** [comment]
There is still tags for twig 2 https://github.com/twigphp/Twig/tags, is it really abandonned ?

**Comment by jordisala1991** [comment]
We are dropping it on next majors anyway, why not do it right away? https://packagist.org/packages/twig/twig#v3.0.0 twig 3 is more than 3 years old...

**Comment by VincentLanglet** [comment]
> We are dropping it on next majors anyway, why not do it right away? [packagist.org/packages/twig/twig#v3.0.0](https://packagist.org/packages/twig/twig#v3.0.0) twig 3 is more than 3 years old...

I just dont know this package enough to know if there was a reason for twig to not abandon the v2. Maybe some people are stuck with v2 for some weird reason...

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
