### PR TITLE
Use block-bundle ^5.0

### PR DESCRIPTION
**Pull request by dmaicher**

### CODE REVIEW

**Comment by dmaicher** [comment]
@franmomu does https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1773 fix those CI test fails? :thinking:

**Comment by VincentLanglet** [comment]
We can confirm this with a cherry-pick

**Comment by VincentLanglet** [comment]
I relaunched the Ci from https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1773, if it pass, I'll merge it.

**Review by VincentLanglet — APPROVED** [review]

**Comment by franmomu** [comment]
> @franmomu does #1773 fix those CI test fails? 🤔

that's what the idea, but I wasn't sure, glad that it worked at least temporarily

**Pull request merged**
