### PR TITLE
3.x into Master

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Need https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1283 first

**Comment by franmomu** [comment]
just curiosity, why are here commits that were apparently merged in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1277?

**Comment by VincentLanglet** [comment]
> just curiosity, why are here commits that were apparently merged in #1277?

It was a squash merge.
He couldnt push to master and I couldn't rebase and master

**Comment by VincentLanglet** [comment]
```
<!-- No admin found for the class &quot;Sonata\DoctrineORMAdminBundle\Tests\App\Entity\Command&quot;, please use the admin_code option instead (500 Internal Server Error) -->
```

**Comment by VincentLanglet** [comment]
It's kinda difficult to check there is an admin for the `$fieldDescription` before calling `attachAdminClass`.
Maybe we should remove the exception in the case of no admin_code is provided and no admin class is found.

WDYT @contributor ?

**Review by dmaicher — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Please take a look @sonata-project/contributors

**Comment by dmaicher** [comment]
I will continue with https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1281 once this one was merged

**Review by franmomu — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Done @dmaicher

**Pull request merged**
