### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by dmaicher**

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
I know nothing about panther, if needed maybe @franmomu can help for the tests.

**Comment by dmaicher** [comment]
> I know nothing about panther, if needed maybe @franmomu can help for the tests.

Makes me think again: do we really need e2e tests that use a browser and execute javascript? Can't we use the (far more reliable) normal `WebTestCase`?

**Comment by franmomu** [comment]
> > I know nothing about panther, if needed maybe @franmomu can help for the tests.
> 
> Makes me think again: do we really need e2e tests that use a browser and execute javascript? Can't we use the (far more reliable) normal `WebTestCase`?

There is [this test](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3c25e81347d7873a82c2b13e44b91283b750c5f9/tests/Functional/ManyToOneMappingTest.php#L22) for example that when creating a book, it also creates an author opening a modal box within the same form and I think it's interesting to test that (I don't know if this can be done with `WebTestCase`). Maybe we can use `WebTestCase` for the ones not using javascript.

**Comment by VincentLanglet** [comment]
Seems like test are green now :)

**Comment by VincentLanglet** [comment]
Thanks @dmaicher

**Pull request merged**
