### PR TITLE
Fix deprecation

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

## Changelog

```markdown
### Fixed
- Removed deprecated usage of Admin FormType constants
```

### CODE REVIEW

**Comment by phansys** [comment]
Please, use the PR template in order to know where to focus the review.

**Comment by VincentLanglet** [comment]
> Please, use the PR template in order to know where to focus the review.

There is just one line to focus on...
Is this enough for you ?

**Comment by phansys** [comment]
Sorry, I don't know the context of the deprecation.
Thank you.

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
