### PR TITLE
make filter types public

### PR DESCRIPTION
**Pull request by osavchenko**
Fix service declaration for symfony 4.x compatibility.

### Changed

Make filter type services public

### CODE REVIEW

**Comment by greg0ire** [comment]
Doesn't this work for you: https://github.com/sonata-project/SonataAdminBundle/pull/4813 ?

**Comment by osavchenko** [comment]
No, I got an error related to this services and my fix works good.

**Comment by greg0ire** [comment]
@xymanek please review

**Comment by osavchenko** [comment]
Maybe I miss something but I have installed latest symfony and sonata today from scratch and get error related to services.

**Comment by greg0ire** [comment]
Please check if [this line](https://github.com/sonata-project/SonataAdminBundle/blob/ee81056dbd5e2f9f5f962e88340a8a8ed4178838/src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php#L31) is executed when you get this error. I'm asking this because in the end, those services shouldn't be public, they should be injected wherever they are needed, which means we would revert this.

**Comment by osavchenko** [comment]
Ah, it's not released. Thank you, will use dev version.

**Comment by greg0ire** [comment]
Oh right! This is pretty old though, I'll ask for a release!

**Comment by osavchenko** [comment]
It will be great! Thank you!

**Pull request closed without merging**
