### PR TITLE
3.34.2

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Failure are coming from https://github.com/doctrine/orm/issues/8723 I think

**Review by core23 — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Any idea why the CI is failing @sonata-project/contributors ?

cc @greg0ire I wonder if it's doctrine related.

**Comment by greg0ire** [comment]
Yes we have added type declarations, and apparently there must be a misuse of `cascade` as a string in this bundle.

**Comment by greg0ire** [comment]
See https://github.com/doctrine/orm/issues/8720

**Comment by VincentLanglet** [comment]
Thanks @greg0ire. I will fix the psalm issues.

**Pull request merged**
