### PR TITLE
Add new button in the acton list

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because I can't find a way to add a new button in the action list.

## Changelog

```markdown
### Added
- Added a doc to add a new button in `Action list`.
```

Screenshot 2022-01-10 at 16 47 18

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @eerison, thanks for the contribution.

This docs is not DoctrineORMAdminBundle related IMHO, would it be possible for you to make the PR on SonataAdmin instead ? This will avoid to duplicate docs with https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/.

The whole "4.3. List actions" part should be in SonataAdmin. It would be in the section
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#

**Comment by eerison** [comment]
> https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/

Hey @VincentLanglet now I understand.

I didn't find this part of documentation, But what I thought it should be here because of this line

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1612/files#diff-c88ca892fc4758e29e653727d908932ce650b595055abbd050a2a228ebb679e0L36

I thought, it was de only documentation how to add a custom link 😄 


But I will open a PR to SonataAdminBundle and you can see if it's make sense ;)

**Question 1:**

What do you think to put a note here linking with https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#customizing-the-fields-displayed-on-the-list-page

**Question 2**:

Make sense to remove 

```
 // add custom action links
            ->add('_action', 'actions', [
                'actions' => [
                    'view' => [],
                    'edit' => [],
                ]
            ]);
```

to avoid misunderstand!

**Comment by VincentLanglet** [comment]
> > https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/
> 
> Hey @VincentLanglet now I understand.
> 
> I didn't find this part of documentation, But what I thought it should be here because of this line
> 
> https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1612/files#diff-c88ca892fc4758e29e653727d908932ce650b595055abbd050a2a228ebb679e0L36
> 
> I thought, it was de only documentation how to add a custom link 😄
> 
> But I will open a PR to SonataAdminBundle and you can see if it's make sense ;)

Yeah, some docs are in the persistence bundle doc for no reason.
You can see that https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/#list-actions is duplicated, so it definitely should be in the main doc.

> **Question 1:**
> 
> What do you think to put a note here linking with https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#customizing-the-fields-displayed-on-the-list-page
> 

Sure, it would be better than having the doc on every persistence bundle docs.

> **Question 2**:
> 
> Make sense to remove
> 
> ```
>  // add custom action links
>             ->add('_action', 'actions', [
>                 'actions' => [
>                     'view' => [],
>                     'edit' => [],
>                 ]
>             ]);
> ```
> 
> to avoid misunderstand!

100% agree, it should be on the sonata admin doc instead.

I would say that almost all the full https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/ page are not persistence bundle related and could be on sonata admin instead...

**Comment by eerison** [comment]
I will create a new PR to remove the `list action`, after the Pull request opened in Sonata admin has merged.

**Pull request closed without merging**
