### PR TITLE
Embedded class support

### PR DESCRIPTION
**Pull request by tiger-seo**
this PR introduce possibility to add properties from [doctrine embeddables](http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html) using dot notation

### CODE REVIEW

**Comment by mihai-stancu** [comment]
+1

I closed #483 in favor of this PR.

**Comment by Soullivaneuh** [comment]
Could we have some description of this PR? Which case it resolves?

**Comment by mihai-stancu** [comment]
@tiger-seo perhaps copy #483 description?

**Comment by tiger-seo** [comment]
@Soullivaneuh i've updated the description

**Comment by Soullivaneuh** [comment]
@tiger-seo Thanks. Could you please add tests?

**Comment by mihai-stancu** [comment]
@tiger-seo I can reopen my PR with your code and supply the tests if you're busy.

**Comment by OskarStark** [comment]
:+1:

**Pull request closed without merging**
