### PR TITLE
Allow sortable for standard form view

### PR DESCRIPTION
**Pull request by core23**
Added sortable feature from the table view to the standard form view.
bildschirmfoto 2015-10-09 um 19 30 51

### CODE REVIEW

**Comment by OskarStark** [comment]
great, yesterday i was looking for this feature :smile:

**Comment by OskarStark** [comment]
@core23 what so you think of putting the delete checkbox next to the sortable element?

But in a separate PR, if ...

**Comment by core23** [comment]
I was already thinking about it, but have no idea how it should look like :/

**Comment by core23** [comment]
Could you get this merged @OskarStark?

**Comment by core23** [comment]
I would contribute a bigger refactoring this weekend (https://github.com/sonata-project/SonataAdminBundle/issues/3173). Could you review and merge please? @OskarStark

**Comment by OskarStark** [comment]
Thank you @core23

**Pull request merged**
