### PR TITLE
Adds AJAX error handling & progress feedback to association widgets. Fixes #522.

### LINKED ISSUE #522: No error handling in AJAX calls
Hi,
as the title says, there isn't currently any kind of error handling in the embeded form's AJAX calls.
An example from `edit_orm_one_association_script.html.twig`:

```js
jQuery(form).ajaxSubmit({
    url: '{{ path('sonata_admin_append_form_element', {
        'code': sonata_admin.admin.root.code,
        'elementId': id,
        'objectId':  sonata_admin.admin.root.id(sonata_admin.admin.root.subject),
        'uniqid':    sonata_admin.admin.root.uniqid,
        'subclass': app.request.query.get('subclass'),
    } + sonata_admin.field_description.getOption('link_parameters', {})) }}',
    type: "POST",
    dataType: 'html',
    data: { _xml_http_request: true },
    success: function(html) {
        if (!html.length) {
            return;
        }

        jQuery('#field_container_{{ id }}').replaceWith(html); // replace the html

        Admin.shared_setup(jQuery('#field_container_{{ id }}'));

        if(jQuery('input[type="file"]', form).length > 0) {
            jQuery(form).attr('enctype', 'multipart/form-data');
            jQuery(form).attr('encoding', 'multipart/form-data');
        }
        jQuery('#sonata-ba-field-container-{{ id }}').trigger('sonata.add_element');
        jQuery('#field_container_{{ id }}').trigger('sonata.add_element');
    }
});
``` 

As you can see, there's no `error` callback, so if the request fails, it's lost in limbo.
There should be at least some kind of feedback...

### PR DESCRIPTION
**Pull request by ju1ius**
There was previously no error handling nor visual feedback in the widgets implementation.
See issue #522 

Changelog:
* adds progress indicators to inform users that an action is taking place.
* display error messages when a request fails.
* refactored to use unobtrusive javascript, all code now resides in static js files.

### CODE REVIEW

**Comment by core23** [comment]
:+1: I like your PR @ju1ius, but there are two thiings:

1) Please squash your commits
2) Can we move some parts (JavaScript) to the AdminBundle, so we can use it for all other ``Sonata*AdminBundles``?  Refs https://github.com/sonata-project/SonataAdminBundle/issues/3173

**Comment by ju1ius** [comment]
> 1. Please squash your commits

Yes, I know, but I wanted at least to have feedback first, especially because of your point n°2.
I'll happily squash everything if it gets accepted.

> 2. Can we move some parts (JavaScript) to the AdminBundle

This is exactly what I intended to propose once somebody reviewed this one.
The js code for the association handling is currently copy/pasted in the MongoDB admin bundle and the CMF admin bundle. It really shouldn' t be dependent of the orm used, since this is part of the UI.

Also having all the JS/CSS code in one bundle would allow to have a real build/testing setup (eg gulp, babel/flow/mocha/karma/whateverify...), along with some documentation (like "what selectors should I use when I want to style this component?").

Also it would allow to provide clean hooks so that people can extend the js functionalities without having to copy/paste large templates or resorting to evil hacks (like setting up DOM MutationObservers to add custom actions to the form fields :sob:).

Part of this code could also be extracted in a public utility library (like the [getField](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/525/files#diff-0ff9a2ad63e6b5a923d7c733018be815R44), [getFieldContainer](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/525/files#diff-0ff9a2ad63e6b5a923d7c733018be815R53) functions).

Should I make a PR to AdminBundle and then 3 PRs to remove the code from the Doctrine/Mongo/CMF bundles ?

**Comment by core23** [comment]
> Should I make a PR to AdminBundle and then 3 PRs to remove the code from the Doctrine/Mongo/CMF bundles ?

That would be great :+1:

**Comment by ju1ius** [comment]
@core23 Ok I'll see what I can come up with in the weekend.

**Comment by ju1ius** [comment]
@core23 I see that the assets are split between the core and admin bundles.

Could you explain to me what should go in Core and what should go in Admin ?

**Comment by ju1ius** [comment]
@core23 Because I have the feeling that some of this stuff really should belong to core-bundle.
Centralizing the js code involves, across all bundles:
* usage of semantic CSS classes & DOM attributes that should be documented and used consistently across all the project's bundle
* a mechanism to pass admin data to the client-side
* a mechanism to pass i18n data to the client-side
* Javascript (+Twig?) helpers to access and manipulate this data without relying on a stringly-type api.

> The SonataCoreBundle provided defaults elements required by the different Sonata’s Bundles.

Or maybe a better move would be to move all frontend stuff to a separate bundle, like ezplatform's [PlatformUIAssetsBundle](https://github.com/ezsystems/PlatformUIAssetsBundle) & [PlatformUIBundle](https://github.com/ezsystems/PlatformUIBundle) ?

Anyway I'll try to stuff everything in AdminBundle first and get the thing working, but I just wondered...

**Comment by core23** [comment]
@ju1ius the CoreBundle is a bundle for all different sonata packages (frontend, backend, misc stuff), the AdminBundle contains all stuff for the backend / admin functionality. 

IMO you could put all stuff to the AdminBundle, because I see no general things that other bundles could use. Later we could discuss to splitt the AdminBundle in a AdminFrontendBundle and AdminBackendBundle.

**Comment by ju1ius** [comment]
@core23 Once When I submit my PR to AdminBundle, should I submit a new one to DoctrineORMAdmin, or just update this one ?

**Comment by core23** [comment]
It's up to you, if you want to leave this PR for history or use this for the final change @ju1ius

**Comment by ju1ius** [comment]
@core23 Ok
I have the thing working now. Now needs to check mongo/cmf/propel...
I was thinking of adding some twig functions to ease the process, like:

```twig
{{ render_the_json_data_for_the_javascript_of_the_button(whatever, needed) }}
```
What do you think ?

**Comment by core23** [comment]
Can't imagine the concrete use of it. Can you give me an example where this function could be used? IMO it's only called in one template in each bundle. @ju1ius

**Comment by ju1ius** [comment]
> IMO it's only called in one template in each bundle.

 Nope, it's called in each `Sonata*AdminBundle:CRUD:edit_*_n_to_n.html.twig`, so 4 times per bundle, and there are 4 AdminBundles.

Here's what it looks like:

```php
    /**
     * {@inheritdoc}
     */
    public function getFunctions()
    {
        return array(
            // ...
            new \Twig_SimpleFunction('sonata_field_description_json', array($this, 'renderFieldDescriptionJSON'), array(
                'needs_context' => true,
                'is_safe' => array('html')
            )),
        );
    }
    /**
     * @param array $context The current Twig context.
     *
     * @return string
     */
    public function renderFieldDescriptionJSON($context)
    {
        /** @var AppVariable $app */
        $app = $context['app'];
        $sonataAdmin = $context['sonata_admin'];
        /** @var Admin $admin */
        $admin = $sonataAdmin['admin'];
        /** @var FieldDescriptionInterface $fieldDescription */
        $fieldDescription = $sonataAdmin['field_description'];
        $root = $admin->getRoot();
        $associationAdmin = $fieldDescription->getAssociationAdmin();
        $router = $admin->getRouteGenerator();

        $data = [
            'id' => $context['id'],
            'editMode' => $sonataAdmin['edit'],
            'formType' => $fieldDescription->getType(),
            'label' => $associationAdmin->trans($associationAdmin->getLabel(), [], $associationAdmin->getTranslationDomain()),
            'loadingMessage' => $admin->trans('loading_information', [], 'SonataAdminBundle'),
            'routes' => [
                'shortObjectDescription' => $router->generate('sonata_admin_short_object_information', [
                    'objectId' => '__OBJECT_ID__',
                    'uniqid' => $associationAdmin->getUniqid(),
                    'code' => $associationAdmin->getCode(),
                    'linkParameters' => $fieldDescription->getOption('link_parameters')
                ]),
                'retrieveFormElement' => $router->generate('sonata_admin_retrieve_form_element', [
                    'code' => $root->getCode(),
                    'elementId' => $context['id'],
                    'objectId' => $root->id($root->getSubject()),
                    'uniqid' => $root->getUniqid(),
                    'subclass' => $admin->getActiveSubclassCode(),
                ]),
                'appendFormElement' => $router->generate(
                    'sonata_admin_append_form_element',
                    array_merge([
                        'code' => $root->getCode(),
                        'elementId' => $context['id'],
                        'objectId' => $root->id($root->getSubject()),
                        'uniqid' => $root->getUniqid(),
                        'subclass' => $app->getRequest()->query->get('subclass'),
                    ], $fieldDescription->getOption('link_parameters', []))
                ),
            ]
        ];

        return json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    }
```

Can you imagine yourself copy/pasting the twig version of this same code in the 16 different templates ? :wink:

**Comment by ju1ius** [comment]
@core23 @OskarStark Is there a mongo/cmf version of the sandbox available ?

**Comment by OskarStark** [comment]
i don't think so @ju1ius

**Comment by ju1ius** [comment]
@OskarStark @core23 Ok, so it'll take a little bit longer...
I have the PRs almost ready for AdminBundle + DoctrineORM, now i'll have to setup test projects for PhpCR and Mongo. Should be ready by the end of the week.

**Comment by ju1ius** [comment]
@core23 @OskarStark Closing this PR in favour of [this one](https://github.com/sonata-project/SonataAdminBundle/pull/3647)

**Pull request closed without merging**
