### PR TITLE
Ensure the fieldname is never null

### PR DESCRIPTION
**Pull request by greg0ire**
Should fix broken tests since Doctrine 2.6 is out.

### CODE REVIEW

**Comment by greg0ire** [comment]
Argh please approve again guys

**Comment by greg0ire** [comment]
Oh no I touched the wrong comment

**Comment by jordisala1991** [comment]
Ill wait until flintci says its okay

**Comment by greg0ire** [comment]
@jordisala1991 Yaaaaay!

**Comment by jordisala1991** [comment]
Thanks @greg0ire

**Pull request merged**
