### PR TITLE
Add support for Symfony 6

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Part of: https://github.com/sonata-project/dev-kit/issues/1675
Dev-kit PR: https://github.com/sonata-project/dev-kit/pull/1759

## Changelog

```markdown
### Added
- Added support for Symfony 6.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
~Blocked by: https://github.com/doctrine/DoctrineFixturesBundle/pull/353~

Edit: Not blocked anymore, thanks @greg0ire

**Comment by jordisala1991** [comment]
Well, blocked by Symfony Panther 😅

**Comment by jordisala1991** [comment]
@sonata-project/contributors WDYT about this strategy? We can simplify the code once Symfony Panther supports Symfony 6.0

**Comment by VincentLanglet** [comment]
I feel bad adding lot of "todo" in the code we might forget later.
I would nice to get some interest on your panther-PR.
Maybe @OskarStark could help us since he's in the symfony team.

**Comment by jordisala1991** [comment]
> I feel bad adding lot of "todo" in the code we might forget later.
> 
> I would nice to get some interest on your panther-PR.
> 
> Maybe @OskarStark could help us since he's in the symfony team.

I am really interested in finishing the PR too, I can assure you I will come here when its done and solve the todos

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
