### PR TITLE
Replace deprecated constant

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

## Changelog

```markdown
### Fixed
- Removed deprecated usage of Admin FormType constants
```

### CODE REVIEW

**Comment by greg0ire** [comment]
@franmomu another failing build :thinking:

**Comment by greg0ire** [comment]
> No need

Why not? Doesn't it fix a deprecation message? If yes that's an positive impact on the life of our users.

**Comment by VincentLanglet** [comment]
@greg0ire I added a changelog then

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
