### PR TITLE
Table responsive

### PR DESCRIPTION
**Pull request by pierre-H**
I am targetting this branch, because it's a little change

## Changelog

``` markdown
### Fixed
- Make relation table display more responsive
```

### CODE REVIEW

**Comment by pierre-H** [comment]
I am sorry but I don't understand what you're asking to me. The modification is very simple and I don't know what to do.

**Comment by greg0ire** [comment]
> I am sorry but I don't understand what you're asking to me. The modification is very simple and I don't know what to do.

Take a screenshot before the change, and one after the change, and post it please. Also, please fill / remove the "To Do" section, or the "Subject" section, etc…

**Comment by Soullivaneuh** [comment]
> I am sorry but I don't understand what you're asking to me.

The changelog is required for the release process.

And for your case, you edit some html. So it would be better to have before/after screenshots as @greg0ire said to see the difference.

**Comment by Soullivaneuh** [comment]
BTW, I updated your changelog. Keep in mind that a changelog should tell what we done (the end result) and not how it was done. :wink:

**Comment by greg0ire** [comment]
ping @pierre-H

**Comment by OskarStark** [comment]
ping @pierre-H

**Comment by OskarStark** [comment]
@pierre-H wpuld be great if you could finish this PR, only add some screenshots please

**Comment by pierre-H** [comment]
@OskarStark I'm sorry, I don't use Sonata anymore so I have to reproduce the case from zero.

**Pull request closed without merging**
