### PR TITLE
Resolve deprecation notices

### LINKED ISSUE #899: Using deprecated core form types
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.1                                     
sonata-project/block-bundle              3.14.0                     
sonata-project/cache                     2.0.1                      
sonata-project/core-bundle               3.15.1
sonata-project/datagrid-bundle           2.4.0                      
sonata-project/doctrine-extensions       1.1.5                      
sonata-project/doctrine-orm-admin-bundle 3.8.2                      
sonata-project/exporter                  1.11.0  
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.3.1  = v3.3.1  Symfony MonologBundle                  
symfony/phpunit-bridge     v4.2.3  = v4.2.3  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 = v1.10.0 Symfony polyfill backporting ap...
symfony/polyfill-ctype     v1.10.0 = v1.10.0 Symfony polyfill for ctype func...
symfony/polyfill-intl-icu  v1.10.0 = v1.10.0 Symfony polyfill for intl's ICU...
symfony/polyfill-mbstring  v1.10.0 = v1.10.0 Symfony polyfill for the Mbstri...
symfony/polyfill-php56     v1.10.0 = v1.10.0 Symfony polyfill backporting so...
symfony/polyfill-php70     v1.10.0 = v1.10.0 Symfony polyfill backporting so...
symfony/polyfill-php72     v1.10.0 = v1.10.0 Symfony polyfill backporting so...
symfony/polyfill-util      v1.10.0 = v1.10.0 Symfony utilities for portabili...
symfony/security-acl       v3.0.1  = v3.0.1  Symfony Security Component - AC...
symfony/swiftmailer-bundle v3.2.5  = v3.2.5  Symfony SwiftmailerBundle
symfony/symfony            v3.4.22 ~ v4.2.3  The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.1.22 (cli) (built: Sep 15 2018 04:13:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

Some classes (filters and guessers) still use deprecated form types from CoreBundle.

## Steps to reproduce

Start using SonataAdminBundle with SonataDoctrineORMAdminBundle and you will get deprecation messages.

## Expected results

No deprecation messages.

## Actual results

I got messages
```
The Sonata\CoreBundle\Form\Type\EqualType class is deprecated since version 3.x and will be removed in 4.0. Use Sonata\Form\Type\EqualType instead.
The Sonata\CoreBundle\Form\Type\BooleanType class is deprecated since version 3.x and will be removed in 4.0. Use Sonata\Form\Type\BooleanType instead.
```
and so on.

### PR DESCRIPTION
**Pull request by ejkun**
## Subject
Since the FormTypes in `CoreBundle` folder are deprecated, all uses of it should be replaced by FormTypes inside `Form` folder. The `composer.json` file was updated to avoid use of lowest SonataCoreBundle version where `Sonata/Form` namespace is not available.

I am targeting this branch, because branch 3.x is the only affected.

Closes #899 

## Changelog

```markdown
### Changed
- Changed all uses of `FormTypes` of `CoreBundle` folder to `Form` folder
```

### CODE REVIEW

**Comment by greg0ire** [comment]
"depreciation noticies" should be "deprecation notices" in your commit message. Likewise, "depreciated" should be "deprecated"

**Comment by ejkun** [comment]
Sorry, I will fix it in a moment.

**Comment by ejkun** [comment]
@greg0ire, any tips on how to solve the problemas found by Travis CI?

**Comment by TorbenLundsgaard** [comment]
I think you have to require "sonata-project/core-bundle": "^3.14.0" in composer.json

**Comment by ejkun** [comment]
I see, that seems like a BC break. I think I will redo everything with checks to see if the class exists. I think this is possible.

**Comment by TorbenLundsgaard** [comment]
it has been done before so I would wait for feedback from @greg0ire before you redo everything

**Comment by ejkun** [comment]
Ok then, I will wait.

**Comment by greg0ire** [comment]
It's not a BC-break, we follow semver and this is a minor version. Please do as @TorbenLundsgaard said :)

**Comment by ejkun** [comment]
@greg0ire, done.

**Comment by ejkun** [comment]
@greg0ire, Scrutinizer returned error, is this OK? I don't know what it does.

**Comment by OskarStark** [comment]
Its fine, thank you

**Pull request merged**
