### PR TITLE
Use FilterData

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

~Needs https://github.com/sonata-project/SonataAdminBundle/pull/7022~

I am targeting this branch, because this is not BC.

## Changelog

```markdown
### Changed
- Use `FilterData` instead of `array` in filters.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
This can be updated now :)

**Comment by cecicifu** [comment]
Need this fix, btw thanks Fran, solved temporally for me.

**Comment by VincentLanglet** [comment]
Since I was trying to fix the phpstan build in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1421 I will include your commit

**Comment by VincentLanglet** [comment]
Included in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1421

**Pull request closed without merging**
