### PR TITLE
remove EmptyFilter service

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

I am targeting this branch, because its BC.

Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1375

## Changelog

Does it need a changelog? File was removed in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1293

```markdown
### Removed
- removed the deprecated `Sonata\DoctrineORMAdminBundle\Filter\EmptyFilter` service
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
We need a merge 3.x into master

**Comment by eerison** [comment]
> We need a merge 3.x into master

@VincentLanglet I guess it wasn't removed from `3.x` branch

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Resources/config/doctrine_orm_filter_types.xml#L43-L45

**Comment by VincentLanglet** [comment]
Sorry if it wasn't clear.
We need first to merge 3.x into master to fix the tests.

**Comment by eerison** [comment]
> Sorry if it wasn't clear.
> We need first to merge 3.x into master to fix the tests.

Ohhh I see, ok ;)

**Comment by VincentLanglet** [comment]
I made the change here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1380

**Pull request closed without merging**
