### PR TITLE
Delete edit_modal.html.twig

### LINKED ISSUE #956: Getting too many deprecation
Just upgraded to SF 4.4.x and it shows a lot of deprecation:

```
The "SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/list_many_to_many.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_many.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_many_to_many.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:show_orm_many_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/show_many_to_one.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_association_script.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_script.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_modal.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_modal.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:show_orm_one_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/show_one_to_many.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many_sortable_script_tabs.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_many_sortable_script_tabs.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_association_script.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_many_script.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many_sortable_script_table.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_many_sortable_script_table.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:list_orm_one_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/list_one_to_many.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:list_orm_one_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/list_one_to_one.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_many_to_one.html.twig" instead.
Using an "if" condition on "for" tag in "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many_inline_tabs.html.twig" at line 40 is deprecated since Twig 2.10.0, use a "filter" filter or an "if" condition inside the "for" body instead (if your condition depends on a variable updated inside the loop).
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many_inline_tabs.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_many_inline_tabs.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many_inline_table.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_many_inline_table.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/list_many_to_one.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/edit_one_to_one.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:show_orm_many_to_many.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/show_many_to_one.html.twig" instead.
The "SonataDoctrineORMAdminBundle:CRUD:show_orm_one_to_one.html.twig" template is deprecated. Use "@SonataAdmin/CRUD/Association/show_one_to_one.html.twig" instead.
```

### PR DESCRIPTION
**Pull request by napestershine**
## #956 

As these files are implemented in SonataAdminBundle, so these don't need anymore. but keep giving deprecations.

I am targeting this branch, because It fixes deprecations on it.

#956 

Closes #956 

## Changelog

```markdown
### Removed
- Removed deprecated templates
```

### CODE REVIEW

**Comment by napestershine** [comment]
@core23 What should be correct branch ?

**Comment by napestershine** [comment]
Thanks

**Comment by manu-sparheld** [comment]
Is it possible to get a release for it ?

Thanks

**Comment by core23** [comment]
> Is it possible to get a release for it ?
> 
> Thanks

This is a change on the unstable branch, which requires a new major release. This is not possible for us at the moment.

**Pull request merged**
