### PR TITLE
Missing template

### PR DESCRIPTION
**Pull request by Baltox**
### Fixed

- Include bad templates : "sortable_script_table.html.twig" and  "sortable_script_tabs.html.twig"

## Subject

Fix missing template :
Unable to find template "SonataDoctrineORMAdminBundle:CRUD:sortable_script_table.html.twig"

### CODE REVIEW

**Comment by greg0ire** [comment]
Wasn't that fixed in #615 ?

**Comment by greg0ire** [comment]
Same diff, so… closing. But thanks anyway!

**Comment by Baltox** [comment]
I didn't see it, my apologies !
Thanks for your reactivity.

**Comment by greg0ire** [comment]
No problem, thanks for contributing!

**Pull request closed without merging**
