### PR TITLE
Remove useless "mapping_type" option

### LINKED ISSUE #1570: Invalid mapping type on ModelFilter with ModelAutocompleteType
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.2.1  4.2.1  The missing Symfony Admin Generator
sonata-project/block-bundle              4.8.0  4.8.0  Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
sonata-project/doctrine-extensions       1.14.0 1.14.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.1.0  4.1.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.8.0  2.8.0  Lightweight Exporter library
sonata-project/form-extensions           1.12.1 1.12.1 Symfony form extensions
sonata-project/twig-extensions           1.9.0  1.9.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v5.3.7  v5.3.7  Symfony AMQP extension Messenger Bridge
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v5.3.4  v5.3.4  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.3.10 v5.3.10 Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.10 v5.3.10 Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.3.10 v5.3.10 Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.3.4  v5.3.4  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.3.4  v5.3.4  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v5.3.10 v5.3.10 Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.3.8  v5.3.8  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.3.10 v5.3.10 Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.3.7  v5.3.7  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.3.10 v5.3.10 Registers environment variables from a .env file
symfony/error-handler              v5.3.7  v5.3.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.7  v5.3.7  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.3.7  v5.3.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.3.4  v5.3.4  Provides basic utilities for the filesystem
symfony/finder                     v5.3.7  v5.3.7  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.17.2 v1.17.2 Composer plugin for Symfony
symfony/form                       v5.3.10 v5.3.10 Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.3.10 v5.3.10 Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.3.10 v5.3.10 Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.10 v5.3.10 Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.10 v5.3.10 Provides a structured process for converting a Request into a Response
symfony/intl                       v5.3.8  v5.3.8  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/lock                       v5.3.10 v5.3.10 Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mailer                     v5.3.9  v5.3.9  Helps sending emails
symfony/maker-bundle               v1.34.1 v1.34.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.3.10 v5.3.10 Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.3.8  v5.3.8  Allows manipulating MIME messages
symfony/monolog-bridge             v5.3.7  v5.3.7  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v5.3.7  v5.3.7  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.3.8  v5.3.8  Provides password hashing utilities
symfony/phpunit-bridge             v5.3.10 v5.3.10 Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype             v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.3.7  v5.3.7  Executes commands in sub-processes
symfony/property-access            v5.3.8  v5.3.8  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.3.8  v5.3.8  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.3.4  v5.3.4  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.1.1  v2.1.1  PSR HTTP message bridge
symfony/rate-limiter               v5.3.4  v5.3.4  Provides a Token Bucket implementation to rate limit input and output in your application
symfony/redis-messenger            v5.3.10 v5.3.10 Symfony Redis extension Messenger Bridge
symfony/routing                    v5.3.7  v5.3.7  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.3.10 v5.3.10 Enables decoupling PHP applications from global state
symfony/security-acl               v3.2.0  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.3.8  v5.3.8  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.3.10 v5.3.10 Symfony Security Component - Core Library
symfony/security-csrf              v5.3.4  v5.3.4  Symfony Security Component - CSRF Library
symfony/security-guard             v5.3.7  v5.3.7  Symfony Security Component - Guard
symfony/security-http              v5.3.10 v5.3.10 Symfony Security Component - HTTP Integration
symfony/serializer                 v5.3.10 v5.3.10 Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.3.4  v5.3.4  Provides a way to profile code
symfony/string                     v5.3.10 v5.3.10 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v5.3.7  v5.3.7  Provides all the tools needed to build any kind of template system
symfony/translation                v5.3.10 v5.3.10 Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v5.3.7  v5.3.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.3.10 v5.3.10 Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.3.10 v5.3.10 Provides tools to validate values
symfony/var-dumper                 v5.3.10 v5.3.10 Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.8  v5.3.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.3.4  v5.3.4  Manages links between resources
symfony/web-profiler-bundle        v5.3.8  v5.3.8  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v5.3.6  v5.3.6  Loads and dumps YAML files

```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.11 (cli) (built: Sep 23 2021 21:26:24) ( NTS )
```

## Code

After changing:

```php
->add('artists', ModelAutocompleteFilter::class, [
    'field_options' => [
        'property' => [
            'name',
        ],
    ],
])
```

To:

```php
->add('artists', ModelFilter::class, [
    'field_options' => [
        'property' => [
            'name',
        ],
    ],
    'field_type' => ModelAutocompleteType::class,
])
```

My list view doesn't work anymore after filtering. The search in the filter itself works fine.

## Steps to reproduce

I go to the "list" view, then I click on "Filter" a check the field that I want to use, then search in the autocomplete field. That works fine. After click on "Filter" I get the message "An exception has been thrown during the rendering of a template ("Invalid mapping type")":
 
Screenshot 2021-11-04 at 13 39 52

## Expected results

See the results.

## More information

In the Sonata\DoctrineORMAdminBundle\Filter\ModelFilter class, the method "association" throws this exception at line 111. The results of ```$this->getOption('mapping_type')``` is false. It should be one of:

```
$types = [
    ClassMetadata::ONE_TO_ONE,
    ClassMetadata::ONE_TO_MANY,
    ClassMetadata::MANY_TO_MANY,
    ClassMetadata::MANY_TO_ONE,
];
```

The "artists" field of the entity is ManyToMany:

```
    /**
     * @var Collection<int, Artist>
     */
    #[ORM\ManyToMany(targetEntity: 'Artist', mappedBy: 'profiles')]
    private Collection $artists;
```

But this problem happened with all my autocomplete fields that are changed to ModelFilter as changed / described in in PR #1545.

### PR DESCRIPTION
**Pull request by willemverspyck**
## Solves problem with "Invalid Mapping Type"

I am targeting this branch, because BC.

Closes #1570.

## Changelog

```markdown
### Fixed
- Fixed using ModelFilter with ModelAutocompleteType
```

### CODE REVIEW

**Review by VincentLanglet — COMMENTED** [review]
Can you also remove 'mapping_type' => false ?

**Comment by willemverspyck** [comment]
I can remove that, but after searching for "mapping_type" I see this code and that doesn't work:

```
if (ClassMetadata::MANY_TO_MANY === $this->getOption('mapping_type')) {
    $or->add(
        sprintf('%s.%s IS EMPTY', $this->getParentAlias($query, $alias), $this->getFieldName())
    );
} else {
    $or->add($query->getQueryBuilder()->expr()->isNull(
        sprintf('IDENTITY(%s.%s)', $this->getParentAlias($query, $alias), $this->getFieldName())
    ));
}
            
```

**Comment by VincentLanglet** [comment]
I see, the difference between the ModelAutocompleteFilter and the ModelFilter was the fact that the ModelFilter supports empty/null values.

This support is requiring to pass the mapping_type. The mapping_type is set to false by default which is throwing an exception since you're not setting it. What would be interesting is to see if we could determine the mapping type instead of requiring users to pass it.

When we're guessing the mapping type, we're passing
```
$options['mapping_type'] = $fieldDescription->getMappingType();
```

The mapping type seems set in the same time than fieldMapping and AssociationMapping
```
protected function setFieldMapping(array $fieldMapping): void
    {
        $this->fieldMapping = $fieldMapping;

        $this->type = $this->type ?? (string) $fieldMapping['type'];
        $this->mappingType = $this->mappingType ?? $fieldMapping['type'];
    }

    protected function setAssociationMapping(array $associationMapping): void
    {
        $this->associationMapping = $associationMapping;

        $this->type = $this->type ?? (string) $associationMapping['type'];
        $this->mappingType = $this->mappingType ?? $associationMapping['type'];
    }
```

Maybe you can find it directly with `getAssociationMapping` in the Filter instead of relying on the option ?
If so we'll be able to deprecate the mapping_type option of the filter :)

**Comment by VincentLanglet** [comment]
I'll release a patch version soon, and like to add this PR too.
Did you understand my last comment @willemverspyck or do you need more help ? :)

**Comment by VincentLanglet** [comment]
For the psalm issue, the phpdoc might be wrong and https://github.com/sonata-project/SonataAdminBundle/pull/7598 will be needed

**Comment by willemverspyck** [comment]
Hi @VincentLanglet. I used your suggestion and committed it last Friday, after testing it with different situations. But didn’t had time to fix the tests yet. I just fixed the tests and added an extra test for a ManyToMany situation.

I only struggled with phpstan, but you already created a PR for that 👍

I think the tests work now (from command line it did), but Github Actions cancelled some tasks.

**Comment by VincentLanglet** [comment]
Can you try to rebase @willemverspyck ?

**Comment by willemverspyck** [comment]
Done! Tests work again 👍

**Comment by VincentLanglet** [comment]
There is no need to pass the option here too: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/4.x/src/FieldDescription/FilterTypeGuesser.php#L76

**Review by VincentLanglet — DISMISSED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by willemverspyck** [comment]
Hi @VincentLanglet. Removed there 👍

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
I have adapted your changelog to be more focused on what you fixed instead of what you changed on the code.

**Comment by VincentLanglet** [comment]
Thanks

**Pull request merged**
