### PR TITLE
Fix batch delete on entities with json columns (PostgreSQL)

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes issues related with batch delete on entities with json columns. Will still need to remove the jsonb from media-bundle to avoid problem for non postgres users.

## Changelog

```markdown
### Fixed
- Fix batch delete on entities with json columns on PostgreSQL.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Does this fixes your issue @eerison ?

What do you think about it @VincentLanglet ? The code has the distinct since a commit 8 years ago. Can this cause trouble in some edge cases? I do not know in which cases I would want to do a distinct here.

**Comment by eerison** [comment]
> Does this fixes your issue @eerison ?
> 
> What do you think about it @VincentLanglet ? The code has the distinct since a commit 8 years ago. Can this cause trouble in some edge cases? I do not know in which cases I would want to do a distinct here.

Hey @jordisala1991 I tested your Branch and it works ❤️

**Review by eerison — DISMISSED** [review]

**Review by eerison — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
Should we release this as patch or minor? @VincentLanglet

**Comment by VincentLanglet** [comment]
Maybe safer as a minor ?

**Pull request merged**
