### PR TITLE
DevKit updates for master branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
Why is it failing? 🤔

**Comment by OskarStark** [comment]
Ah because of the “.*” 👍🏻

**Comment by jordisala1991** [comment]
Related to this: https://github.com/sonata-project/dev-kit/pull/797

**Comment by greg0ire** [comment]
Now it fails because admin@master requires block@master

**Comment by VincentLanglet** [comment]
> Now it fails because admin@master requires block@master

I will take the travis change in this PR https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1073

**Comment by OskarStark** [comment]
> I will take the travis change in this PR #1073

Now, where Travis is gone, can you add your change to GithubActions?

**Comment by OskarStark** [comment]
Lets get a new one from `dev-kit`

**Pull request closed without merging**
