### PR TITLE
Fix rendering of boolean filter and remove unused private method.

### PR DESCRIPTION
**Pull request by Koc**
Boolean filter should be rendered as choice with yes/no options. Currently it renders like text input.

### CODE REVIEW

**Comment by Koc** [comment]
ping @rande

**Comment by GromNaN** [comment]
I had the same issue. It is fixed on master branch.

**Comment by Koc** [comment]
Does it really fixed? https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/BooleanFilter.php#L57

ping @Soullivaneuh

**Comment by Koc** [comment]
ping @rande @Soullivaneuh @OskarStark

**Comment by OskarStark** [comment]
@GromNaN i think @Koc is right, this isn't fixed yet in master

**Comment by Koc** [comment]
Can anybody merge?

**Comment by OskarStark** [comment]
Thank you @Koc

**Comment by OskarStark** [comment]
@Koc can you port this to master?

**Comment by Koc** [comment]
Are you not merging 2.3 branch into master sometimes?

**Comment by OskarStark** [comment]
to be honest, don't know, maybe sometimes, but i like to take care of merge some PR's explicitley

**Pull request merged**
