### PR TITLE
3.19.0

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by core23** [comment]
Travis is failing :(

**Comment by greg0ire** [comment]
```
163844d9043f0fcf4b1999b5c216fd4a1cbe5f3c is the first bad commit
commit 163844d9043f0fcf4b1999b5c216fd4a1cbe5f3c
Author: wbloszyk <wbloszyk@gmail.com>
Date:   Sat Jun 6 09:25:45 2020 +0200

    Make CoreBundle optional (#1048)
    
    * Make CoreBundle optional
    
    * Fix

 composer.json                  | 2 +-
 src/Builder/FormContractor.php | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)
bisect run success
```

@wbloszyk please help

**Comment by wbloszyk** [comment]
Probably after release BlockBundle 3.20. CoreBundle is not require in dependecies too. Checking.

**Comment by wbloszyk** [comment]
@greg0ire @core23 Fix for it: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1060

**Pull request merged**
